name: CI

on:
  - push

jobs:
  test-build-untracked-file-on-ci:
    runs-on: ubuntu-latest
    env:
      branch: ${{ github.job }}-${{ github.run_id }}
      folder: ${{ github.job }}-${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ${{ env.folder }} && echo hello > ${{ env.folder }}/hello
      - name: Use action
        uses: ./
        with:
          branch: ${{ env.branch }}
          folder: ${{ env.folder }}
      - name: Test
        run: ([[ $(cat ${{ env.folder }}/hello) = hello ]])
        shell: bash
      - name: Clean-up
        run: |
          git push origin :${{ env.branch }}

  test-build-untracked-file-but-tracked-on-gh-pages:
    runs-on: ubuntu-latest
    env:
      branch: ${{ github.job }}-${{ github.run_id }}
      folder: ${{ github.job }}-${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ${{ env.folder }} && echo hello > ${{ env.folder }}/hello
      - name: Create branch
        uses: ./
        with:
          branch: ${{ env.branch }}
          folder: ${{ env.folder }}
      - uses: actions/checkout@v2
      - run: mkdir ${{ env.folder }} && echo HELLO > ${{ env.folder }}/hello
      - name: Use action
        uses: ./
        with:
          branch: ${{ env.branch }}
          folder: ${{ env.folder }}
      - name: Test
        run: ([[ $(cat ${{ env.folder }}/hello) = HELLO ]])
        shell: bash
      - name: Clean-up
        run: |
          git push origin :${{ env.branch }}
